package pl.mkn.incidenttracker.analysis.ai.copilot;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import lombok.RequiredArgsConstructor;
import pl.mkn.incidenttracker.analysis.AnalysisConfidence;
import pl.mkn.incidenttracker.analysis.AnalysisFlowDiagram;
import pl.mkn.incidenttracker.analysis.AnalysisFlowDiagramEdge;
import pl.mkn.incidenttracker.analysis.AnalysisFlowDiagramMetadata;
import pl.mkn.incidenttracker.analysis.AnalysisFlowDiagramNode;
import pl.mkn.incidenttracker.analysis.AnalysisMode;
import pl.mkn.incidenttracker.analysis.AnalysisProblemNature;
import pl.mkn.incidenttracker.analysis.ai.AnalysisAiAnalysisRequest;
import pl.mkn.incidenttracker.analysis.ai.AnalysisAiAnalysisResponse;
import pl.mkn.incidenttracker.analysis.ai.AnalysisAiProvider;
import org.springframework.stereotype.Service;
import pl.mkn.incidenttracker.analysis.ai.copilot.execution.CopilotSdkExecutionGateway;
import pl.mkn.incidenttracker.analysis.ai.copilot.preparation.CopilotSdkPreparationService;

import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

@Service
@Slf4j
@RequiredArgsConstructor
public class CopilotSdkAnalysisAiProvider implements AnalysisAiProvider {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
    private static final List<String> EXPECTED_FIELD_LABELS = List.of(
            "detectedProblem",
            "summary",
            "recommendedAction",
            "rationale",
            "problemNature",
            "confidence",
            "diagram"
    );

    private final CopilotSdkPreparationService preparationService;
    private final CopilotSdkExecutionGateway executionGateway;

    @Override
    public String preparePrompt(AnalysisAiAnalysisRequest request) {
        return preparationService.prepare(request).prompt();
    }

    @Override
    public AnalysisAiAnalysisResponse analyze(AnalysisAiAnalysisRequest request) {
        var analysisStart = System.nanoTime();
        var preparedRequest = preparationService.prepare(request);
        var assistantContent = executionGateway.execute(preparedRequest);
        var response = mapAssistantContent(
                request.mode(),
                request.correlationId(),
                assistantContent,
                preparedRequest.prompt()
        );

        log.info(
                "Copilot analysis completed correlationId={} durationMs={} detectedProblem={} structuredResponse={}",
                request.correlationId(),
                (System.nanoTime() - analysisStart) / 1_000_000,
                response.detectedProblem(),
                !"AI_UNSTRUCTURED_RESPONSE".equals(response.detectedProblem())
        );

        return response;
    }

    private AnalysisAiAnalysisResponse mapAssistantContent(
            AnalysisMode mode,
            String correlationId,
            String assistantContent,
            String prompt
    ) {
        var fields = parseLabeledFields(assistantContent);
        var detectedProblem = fields.get("detectedproblem");
        var summary = fields.get("summary");
        var recommendedAction = fields.get("recommendedaction");
        var rationale = fields.get("rationale");
        var problemNature = parseProblemNature(fields.get("problemnature"), mode);
        var confidence = parseConfidence(fields.get("confidence"), mode);
        var diagram = parseDiagram(fields.get("diagram"), mode, correlationId);

        log.info(
                "Copilot response parse correlationId={} parsedKeys={} structuredResponse={}",
                correlationId,
                fields.keySet(),
                detectedProblem != null && summary != null && recommendedAction != null
        );

        if (detectedProblem == null || summary == null || recommendedAction == null) {
            return new AnalysisAiAnalysisResponse(
                    "copilot-sdk",
                    assistantContent,
                    "AI_UNSTRUCTURED_RESPONSE",
                    "Review the raw Copilot response and improve response formatting in the prompt.",
                    "Generated by GitHub Copilot SDK from the prepared diagnostic evidence.",
                    problemNature,
                    confidence,
                    prompt,
                    diagram
            );
        }

        return new AnalysisAiAnalysisResponse(
                "copilot-sdk",
                summary,
                detectedProblem,
                recommendedAction,
                rationale != null
                        ? rationale
                        : "Generated by GitHub Copilot SDK from the prepared diagnostic evidence.",
                problemNature,
                confidence,
                prompt,
                diagram
        );
    }

    private Map<String, String> parseLabeledFields(String assistantContent) {
        var fields = new HashMap<String, String>();
        String currentKey = null;
        StringBuilder currentValue = null;

        for (var line : assistantContent.split("\\R")) {
            var fieldDeclaration = parseFieldDeclaration(line);
            if (fieldDeclaration != null) {
                storeCurrentField(fields, currentKey, currentValue);
                currentKey = fieldDeclaration.key();
                currentValue = new StringBuilder(fieldDeclaration.initialValue());
                continue;
            }

            if (currentKey == null || currentValue == null) {
                continue;
            }

            var trimmedLine = line.trim();
            if (trimmedLine.isEmpty()) {
                if (currentValue.length() > 0 && !endsWithNewline(currentValue)) {
                    currentValue.append("\n\n");
                }
                continue;
            }

            if (currentValue.length() > 0 && !endsWithNewline(currentValue)) {
                currentValue.append('\n');
            }
            currentValue.append(trimmedLine);
        }

        storeCurrentField(fields, currentKey, currentValue);
        return fields;
    }

    private void storeCurrentField(Map<String, String> fields, String key, StringBuilder value) {
        if (key == null || value == null) {
            return;
        }

        var normalizedValue = value.toString().trim();
        if (!normalizedValue.isEmpty()) {
            fields.put(key, normalizeStructuredFieldValue(key, normalizedValue));
        }
    }

    private FieldDeclaration parseFieldDeclaration(String rawLine) {
        var trimmedLine = rawLine.trim();
        if (trimmedLine.isEmpty()) {
            return null;
        }

        var normalizedLine = trimmedLine
                .replaceFirst("^[-+*]\\s+", "")
                .replaceFirst("^>\\s+", "")
                .replaceFirst("^\\d+[.)]\\s+", "");
        for (var label : EXPECTED_FIELD_LABELS) {
            var initialValue = extractFieldValue(normalizedLine, label);
            if (initialValue != null) {
                return new FieldDeclaration(normalizeFieldKey(label), initialValue.trim());
            }
        }

        return null;
    }

    private String extractFieldValue(String line, String fieldLabel) {
        var lowerLine = line.toLowerCase(Locale.ROOT);
        var lowerFieldLabel = fieldLabel.toLowerCase(Locale.ROOT);

        if (lowerLine.startsWith(lowerFieldLabel + ":")) {
            return line.substring(fieldLabel.length() + 1);
        }

        for (var wrapper : List.of("**", "__", "`")) {
            var wrappedColonInside = wrapper + lowerFieldLabel + ":" + wrapper;
            if (lowerLine.startsWith(wrappedColonInside)) {
                return line.substring(wrapper.length() + fieldLabel.length() + 1 + wrapper.length());
            }

            var wrappedColonOutside = wrapper + lowerFieldLabel + wrapper + ":";
            if (lowerLine.startsWith(wrappedColonOutside)) {
                return line.substring(wrapper.length() + fieldLabel.length() + wrapper.length() + 1);
            }
        }

        return null;
    }

    private String normalizeFieldKey(String rawKey) {
        return rawKey.trim()
                .toLowerCase(Locale.ROOT)
                .replaceAll("^[\\-*+>#\\d.()\\s`_]+", "")
                .replaceAll("[*_`\\s-]+", "")
                .replaceAll("[^a-z0-9]", "");
    }

    private String normalizeStructuredFieldValue(String key, String rawValue) {
        var normalized = rawValue.trim();

        if ("summary".equals(key)) {
            return normalizeLegacyPipeBullets(normalized, false);
        }

        if ("recommendedaction".equals(key) || "rationale".equals(key)) {
            return normalizeLegacyPipeBullets(normalized, true);
        }

        return normalized;
    }

    private String normalizeLegacyPipeBullets(String value, boolean bulletizeFirstSegment) {
        if (!value.contains("| -")) {
            return value;
        }

        var normalized = value.replaceAll("\\s*\\|\\s+-\\s+", "\n- ");
        if (bulletizeFirstSegment && !normalized.startsWith("- ")) {
            return "- " + normalized;
        }

        return normalized;
    }

    private boolean endsWithNewline(StringBuilder value) {
        var current = value.toString();
        return current.endsWith("\n") || current.endsWith("\n\n");
    }

    private AnalysisProblemNature parseProblemNature(String rawValue, AnalysisMode mode) {
        if (rawValue != null) {
            try {
                return AnalysisProblemNature.valueOf(rawValue.trim().toUpperCase(Locale.ROOT));
            } catch (IllegalArgumentException exception) {
                log.debug("Unknown problemNature from Copilot response: {}", rawValue);
            }
        }

        return mode == AnalysisMode.EXPLORATORY
                ? AnalysisProblemNature.HYPOTHESIS
                : AnalysisProblemNature.CONFIRMED;
    }

    private AnalysisConfidence parseConfidence(String rawValue, AnalysisMode mode) {
        if (rawValue != null) {
            try {
                return AnalysisConfidence.valueOf(rawValue.trim().toUpperCase(Locale.ROOT));
            } catch (IllegalArgumentException exception) {
                log.debug("Unknown confidence from Copilot response: {}", rawValue);
            }
        }

        return mode == AnalysisMode.EXPLORATORY
                ? AnalysisConfidence.MEDIUM
                : AnalysisConfidence.HIGH;
    }

    private AnalysisFlowDiagram parseDiagram(String rawValue, AnalysisMode mode, String correlationId) {
        if (mode != AnalysisMode.EXPLORATORY || rawValue == null || rawValue.isBlank()) {
            return null;
        }

        var normalized = stripCodeFence(rawValue);
        if ("null".equalsIgnoreCase(normalized.trim())) {
            return null;
        }

        try {
            var root = OBJECT_MAPPER.readTree(normalized);
            if (root == null || root.isNull()) {
                return null;
            }

            return new AnalysisFlowDiagram(
                    parseNodes(root.path("nodes")),
                    parseEdges(root.path("edges"))
            );
        } catch (Exception exception) {
            log.warn(
                    "Copilot exploratory diagram parse failed correlationId={} rawValue={}",
                    correlationId,
                    rawValue,
                    exception
            );
            return null;
        }
    }

    private List<AnalysisFlowDiagramNode> parseNodes(JsonNode nodesNode) {
        if (!nodesNode.isArray()) {
            return List.of();
        }

        var nodes = new java.util.ArrayList<AnalysisFlowDiagramNode>();
        for (var node : nodesNode) {
            nodes.add(new AnalysisFlowDiagramNode(
                    readText(node, "id"),
                    readText(node, "kind"),
                    readText(node, "title"),
                    readText(node, "componentName"),
                    readText(node, "factStatus"),
                    readText(node, "firstSeenAt"),
                    parseMetadata(node.path("metadata")),
                    node.path("errorSource").asBoolean(false)
            ));
        }
        return List.copyOf(nodes);
    }

    private List<AnalysisFlowDiagramEdge> parseEdges(JsonNode edgesNode) {
        if (!edgesNode.isArray()) {
            return List.of();
        }

        var edges = new java.util.ArrayList<AnalysisFlowDiagramEdge>();
        for (var edge : edgesNode) {
            edges.add(new AnalysisFlowDiagramEdge(
                    readText(edge, "id"),
                    readText(edge, "fromNodeId"),
                    readText(edge, "toNodeId"),
                    edge.path("sequence").asInt(0),
                    readText(edge, "interactionType"),
                    readText(edge, "factStatus"),
                    readText(edge, "startedAt"),
                    edge.path("durationMs").isNumber() ? edge.path("durationMs").asLong() : null,
                    readText(edge, "supportSummary")
            ));
        }
        return List.copyOf(edges);
    }

    private List<AnalysisFlowDiagramMetadata> parseMetadata(JsonNode metadataNode) {
        if (!metadataNode.isArray()) {
            return List.of();
        }

        var metadata = new java.util.ArrayList<AnalysisFlowDiagramMetadata>();
        for (var entry : metadataNode) {
            metadata.add(new AnalysisFlowDiagramMetadata(
                    readText(entry, "name"),
                    readText(entry, "value")
            ));
        }
        return List.copyOf(metadata);
    }

    private String readText(JsonNode node, String fieldName) {
        var value = node.path(fieldName);
        return value.isMissingNode() || value.isNull() ? "" : value.asText("");
    }

    private String stripCodeFence(String rawValue) {
        var normalized = rawValue.trim();
        if (!normalized.startsWith("```")) {
            return normalized;
        }

        normalized = normalized.replaceFirst("^```[a-zA-Z0-9_-]*\\s*", "");
        normalized = normalized.replaceFirst("\\s*```$", "");
        return normalized.trim();
    }

    private record FieldDeclaration(String key, String initialValue) {
    }

}
