package pl.mkn.incidenttracker.analysis.ai.copilot.response;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;
import pl.mkn.incidenttracker.analysis.ai.copilot.response.CopilotResponseDtos.EvidenceReference;
import pl.mkn.incidenttracker.analysis.ai.copilot.response.CopilotResponseDtos.ParseResult;
import pl.mkn.incidenttracker.analysis.ai.copilot.response.CopilotResponseDtos.StructuredAnalysisResponse;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

@Component
@RequiredArgsConstructor
public class CopilotResponseParser {

    private static final String DEFAULT_RECOMMENDED_ACTION =
            "Review the raw Copilot response and improve response formatting in the prompt.";
    private static final String DEFAULT_SUMMARY =
            "Copilot response did not contain a parseable summary.";
    private static final String DEFAULT_RATIONALE =
            "Generated by GitHub Copilot SDK from the prepared diagnostic evidence.";
    private static final Pattern FENCED_JSON_PATTERN = Pattern.compile(
            "```(?:json|JSON)?\\s*([\\s\\S]*?)\\s*```",
            Pattern.DOTALL
    );

    private final ObjectMapper objectMapper;

    public ParseResult parse(String assistantContent) {
        var fullJson = parseJsonNode(assistantContent);
        if (fullJson != null) {
            return resultFromResponse(
                    responseFromJson(fullJson),
                    assistantContent,
                    parsedJsonFields(fullJson)
            );
        }

        var fencedJson = extractFencedJson(assistantContent);
        if (fencedJson != null) {
            var fencedNode = parseJsonNode(fencedJson);
            if (fencedNode != null) {
                return resultFromResponse(
                        responseFromJson(fencedNode),
                        assistantContent,
                        parsedJsonFields(fencedNode)
                );
            }
        }

        return fallbackResult(null, assistantContent, List.of());
    }

    private ParseResult resultFromResponse(
            StructuredAnalysisResponse parsedResponse,
            String assistantContent,
            List<String> parsedFields
    ) {
        if (hasRequiredFields(parsedResponse)) {
            return new ParseResult(
                    normalizeResponse(parsedResponse),
                    true,
                    false,
                    parsedFields
            );
        }

        return fallbackResult(parsedResponse, assistantContent, parsedFields);
    }

    private ParseResult fallbackResult(
            StructuredAnalysisResponse parsedResponse,
            String assistantContent,
            List<String> parsedFields
    ) {
        return new ParseResult(
                fallbackResponse(parsedResponse, assistantContent),
                false,
                true,
                parsedFields
        );
    }

    private StructuredAnalysisResponse fallbackResponse(
            StructuredAnalysisResponse parsedResponse,
            String assistantContent
    ) {
        return new StructuredAnalysisResponse(
                firstText(parsedResponse != null ? parsedResponse.detectedProblem() : null, "AI_UNSTRUCTURED_RESPONSE"),
                firstText(
                        parsedResponse != null ? parsedResponse.summary() : null,
                        firstText(assistantContent, DEFAULT_SUMMARY)
                ),
                firstText(parsedResponse != null ? parsedResponse.recommendedAction() : null, DEFAULT_RECOMMENDED_ACTION),
                firstText(parsedResponse != null ? parsedResponse.rationale() : null, DEFAULT_RATIONALE),
                firstText(parsedResponse != null ? parsedResponse.affectedFunction() : null, ""),
                firstText(parsedResponse != null ? parsedResponse.affectedProcess() : null, ""),
                firstText(parsedResponse != null ? parsedResponse.affectedBoundedContext() : null, ""),
                firstText(parsedResponse != null ? parsedResponse.affectedTeam() : null, ""),
                firstText(parsedResponse != null ? parsedResponse.confidence() : null, null),
                parsedResponse != null ? parsedResponse.evidenceReferences() : List.of(),
                parsedResponse != null ? parsedResponse.visibilityLimits() : List.of()
        );
    }

    private StructuredAnalysisResponse normalizeResponse(StructuredAnalysisResponse response) {
        return new StructuredAnalysisResponse(
                response.detectedProblem(),
                response.summary(),
                response.recommendedAction(),
                firstText(response.rationale(), DEFAULT_RATIONALE),
                response.affectedFunction(),
                firstText(response.affectedProcess(), ""),
                firstText(response.affectedBoundedContext(), ""),
                firstText(response.affectedTeam(), ""),
                firstText(response.confidence(), null),
                response.evidenceReferences(),
                response.visibilityLimits()
        );
    }

    private boolean hasRequiredFields(StructuredAnalysisResponse response) {
        return response != null
                && StringUtils.hasText(response.detectedProblem())
                && StringUtils.hasText(response.summary())
                && StringUtils.hasText(response.recommendedAction())
                && StringUtils.hasText(response.affectedFunction());
    }

    private JsonNode parseJsonNode(String candidate) {
        if (!StringUtils.hasText(candidate)) {
            return null;
        }

        try {
            var node = objectMapper.readTree(candidate.trim());
            return node != null && node.isObject() ? node : null;
        }
        catch (IOException exception) {
            return null;
        }
    }

    private String extractFencedJson(String assistantContent) {
        if (!StringUtils.hasText(assistantContent)) {
            return null;
        }

        var matcher = FENCED_JSON_PATTERN.matcher(assistantContent);
        return matcher.find() ? matcher.group(1) : null;
    }

    private StructuredAnalysisResponse responseFromJson(JsonNode node) {
        return new StructuredAnalysisResponse(
                text(node, "detectedProblem"),
                text(node, "summary"),
                text(node, "recommendedAction"),
                text(node, "rationale"),
                text(node, "affectedFunction"),
                text(node, "affectedProcess"),
                text(node, "affectedBoundedContext"),
                text(node, "affectedTeam"),
                text(node, "confidence"),
                evidenceReferences(node.get("evidenceReferences")),
                visibilityLimits(node.get("visibilityLimits"))
        );
    }

    private String text(JsonNode node, String fieldName) {
        if (node == null || !node.has(fieldName) || node.get(fieldName).isNull()) {
            return null;
        }

        var field = node.get(fieldName);
        if (field.isValueNode()) {
            var value = field.asText();
            return StringUtils.hasText(value) ? value.trim() : null;
        }

        return field.toString();
    }

    private List<EvidenceReference> evidenceReferences(JsonNode node) {
        if (node == null || !node.isArray()) {
            return List.of();
        }

        var references = new ArrayList<EvidenceReference>();
        for (var item : node) {
            if (!item.isObject()) {
                continue;
            }
            references.add(new EvidenceReference(
                    text(item, "field"),
                    text(item, "artifactId"),
                    text(item, "itemId"),
                    text(item, "claim")
            ));
        }

        return List.copyOf(references);
    }

    private List<String> visibilityLimits(JsonNode node) {
        if (node == null || !node.isArray()) {
            return List.of();
        }

        var limits = new ArrayList<String>();
        for (var item : node) {
            if (item.isValueNode() && StringUtils.hasText(item.asText())) {
                limits.add(item.asText().trim());
            }
            else if (item.isObject()) {
                var description = text(item, "description");
                if (description != null) {
                    limits.add(description);
                }
            }
        }

        return List.copyOf(limits);
    }

    private List<String> parsedJsonFields(JsonNode node) {
        if (node == null || !node.isObject()) {
            return List.of();
        }

        var fields = new ArrayList<String>();
        node.fieldNames().forEachRemaining(fields::add);
        return List.copyOf(fields);
    }

    private String firstText(String value, String fallback) {
        return StringUtils.hasText(value) ? value.trim() : fallback;
    }
}
