[CmdletBinding()]
param(
    [string] $BaseUrl = "http://localhost:8080",
    [string] $OutputPath = (Join-Path $PSScriptRoot "validation-findings.md"),
    [switch] $FailOnError
)

$ErrorActionPreference = "Stop"

function Escape-MarkdownCell {
    param([object] $Value)

    if ($null -eq $Value) {
        return ""
    }

    return ([string] $Value).
        Replace("|", "\|").
        Replace("`r", " ").
        Replace("`n", " ").
        Trim()
}

function First-SourceRef {
    param([object] $Finding)

    if ($Finding.sourceRefs -and $Finding.sourceRefs.Count -gt 0) {
        return $Finding.sourceRefs[0]
    }

    return $null
}

function Count-Where {
    param(
        [object[]] $Items,
        [string] $Property,
        [string] $Value
    )

    return @($Items | Where-Object { $_.$Property -eq $Value }).Count
}

function Add-CountTable {
    param(
        [System.Collections.Generic.List[string]] $Lines,
        [string] $Title,
        [object[]] $Rows,
        [string] $NameHeader
    )

    $Lines.Add("")
    $Lines.Add("## $Title")
    $Lines.Add("")
    $Lines.Add("| $NameHeader | Count |")
    $Lines.Add("| --- | ---: |")

    foreach ($row in $Rows) {
        $Lines.Add("| $(Escape-MarkdownCell $row.Name) | $($row.Count) |")
    }
}

$uri = "$($BaseUrl.TrimEnd('/'))/api/operational-context/validation"
$response = Invoke-RestMethod -Uri $uri -Method Get
$findings = if ($null -eq $response) {
    @()
} elseif ($response -is [System.Array]) {
    $response
} else {
    @($response)
}

$records = @($findings | ForEach-Object {
    $sourceRef = First-SourceRef $_
    [pscustomobject]@{
        Severity     = $_.severity
        Category     = $_.category
        EntityType   = $_.entityType
        EntityId     = $_.entityId
        Title        = $_.title
        Detail       = $_.detail
        SuggestedFix = $_.suggestedFix
        Impact       = $_.impact
        File         = if ($sourceRef) { $sourceRef.file } else { "" }
        Path         = if ($sourceRef) { $sourceRef.path } else { "" }
    }
})

$generatedAt = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
$severityOrder = @("error", "warning", "info")
$lines = [System.Collections.Generic.List[string]]::new()

$lines.Add("# Operational context validation findings")
$lines.Add("")
$lines.Add("Generated: ``$generatedAt``")
$lines.Add("")
$lines.Add("Source: ``$uri``")
$lines.Add("")
$lines.Add('This file is generated by `operational-context-maintenance/update-validation-findings.ps1`.')
$lines.Add("Use it as a deterministic maintenance checkpoint before and after catalog updates.")
$lines.Add("")
$lines.Add("## Summary")
$lines.Add("")
$lines.Add("| Severity | Count |")
$lines.Add("| --- | ---: |")
foreach ($severity in $severityOrder) {
    $lines.Add("| $severity | $(Count-Where $records Severity $severity) |")
}
$lines.Add("| total | $($records.Count) |")

$warningGroups = @($records |
    Where-Object { $_.Severity -eq "warning" } |
    Group-Object Category, Title, EntityType, File |
    Sort-Object @{ Expression = "Count"; Descending = $true }, Name)

$errorCount = Count-Where $records Severity "error"
$lines.Add("")
$lines.Add("## Start-of-run focus")
$lines.Add("")
if ($errorCount -gt 0) {
    $lines.Add('- Fix `error` findings first; they indicate broken references or unusable operational context API data.')
} else {
    $lines.Add('- No `error` findings were reported in the latest snapshot.')
}
if ($warningGroups.Count -gt 0) {
    $lines.Add("- Review the largest warning groups before asking an LLM to update YAML/MD:")
    foreach ($group in @($warningGroups | Select-Object -First 5)) {
        $sample = $group.Group[0]
        $lines.Add("  - ``$($sample.Category)`` / ``$($sample.Title)`` / ``$($sample.EntityType)`` / ``$($sample.File)``: $($group.Count)")
    }
} else {
    $lines.Add("- No warning groups were reported.")
}
$lines.Add('- Treat `info` findings as maintenance backlog unless they block a concrete handoff or operator workflow.')

Add-CountTable $lines "By category" (@($records | Group-Object Category | Sort-Object @{ Expression = "Count"; Descending = $true }, Name)) "Category"
Add-CountTable $lines "By source file" (@($records | Group-Object File | Sort-Object @{ Expression = "Count"; Descending = $true }, Name)) "Source file"
Add-CountTable $lines "By entity type" (@($records | Group-Object EntityType | Sort-Object @{ Expression = "Count"; Descending = $true }, Name)) "Entity type"

$lines.Add("")
$lines.Add("## Grouped findings")

foreach ($severity in $severityOrder) {
    $severityRecords = @($records | Where-Object { $_.Severity -eq $severity })
    if ($severityRecords.Count -eq 0) {
        continue
    }

    $lines.Add("")
    $lines.Add("## $severity")

    $groups = @($severityRecords |
        Group-Object Category, Title, EntityType, File |
        Sort-Object @{ Expression = "Count"; Descending = $true }, Name)

    foreach ($group in $groups) {
        $sample = $group.Group[0]
        $lines.Add("")
        $lines.Add("### $($sample.Category) / $($sample.Title) / $($sample.EntityType) / $($sample.File) ($($group.Count))")
        $lines.Add("")
        $lines.Add("| Entity | Path | Detail | Suggested fix | Impact |")
        $lines.Add("| --- | --- | --- | --- | --- |")

        foreach ($finding in @($group.Group | Sort-Object EntityId, Path, Detail)) {
            $lines.Add("| $(Escape-MarkdownCell $finding.EntityId) | $(Escape-MarkdownCell $finding.Path) | $(Escape-MarkdownCell $finding.Detail) | $(Escape-MarkdownCell $finding.SuggestedFix) | $(Escape-MarkdownCell $finding.Impact) |")
        }
    }
}

$outputDirectory = Split-Path -Parent $OutputPath
if ($outputDirectory -and -not (Test-Path -Path $outputDirectory)) {
    New-Item -Path $outputDirectory -ItemType Directory | Out-Null
}

$lines | Set-Content -Path $OutputPath -Encoding UTF8

Write-Output "Wrote $($records.Count) findings to $OutputPath"

if ($FailOnError -and $errorCount -gt 0) {
    throw "Operational context validation reported $errorCount error finding(s)."
}
